SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT U.USER_ID) USERS
FROM USER_INFO AS U
JOIN ONLINE_SALE AS S
ON U.USER_ID = S.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER;